//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_GIA_IN_NHANH
    {
        public int ID { get; set; }
        public string ten_bang_gia { get; set; }
        public string mo_ta { get; set; }
        public string day_so_luong { get; set; }
        public string day_gia { get; set; }
        public Nullable<int> thu_tu { get; set; }
        public Nullable<bool> khong_su_dung { get; set; }
        public Nullable<int> ID_HANG_KHACH_HANG { get; set; }
        public Nullable<int> so_trang_toi_da { get; set; }
        public string noi_dung_bang_gia { get; set; }
        public string day_so_luong_niem_yet { get; set; }
        public string don_vi_tinh { get; set; }
        public Nullable<bool> gia_theo_khoang { get; set; }
    
        public virtual HANG_KHACH_HANG HANG_KHACH_HANG { get; set; }
    }
}
