//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_MUC_GIAY
    {
        public DANH_MUC_GIAY()
        {
            this.MARK_UP_LOI_NHUAN_GIAY = new HashSet<MARK_UP_LOI_NHUAN_GIAY>();
            this.GIAYs = new HashSet<GIAY>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Nha_cung_cap { get; set; }
        public Nullable<int> Thu_tu { get; set; }
    
        public virtual ICollection<MARK_UP_LOI_NHUAN_GIAY> MARK_UP_LOI_NHUAN_GIAY { get; set; }
        public virtual ICollection<GIAY> GIAYs { get; set; }
    }
}
