//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_THANH_PHAM
    {
        public int ID { get; set; }
        public string ten { get; set; }
        public string ma_01 { get; set; }
        public string ma_02 { get; set; }
        public string ma_03 { get; set; }
        public string don_vi_tinh { get; set; }
        public string day_so_luong { get; set; }
        public Nullable<int> thu_tu { get; set; }
    }
}
