//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAY
    {
        public int ID { get; set; }
        public string Ma_giay_ncc { get; set; }
        public string Ma_giay_tu_dat { get; set; }
        public string Ten_giay { get; set; }
        public string Dien_giai { get; set; }
        public Nullable<int> Dinh_luong { get; set; }
        public string Kho_giay { get; set; }
        public Nullable<double> Chieu_ngan { get; set; }
        public Nullable<double> Chieu_dai { get; set; }
        public Nullable<int> Gia_mua { get; set; }
        public Nullable<int> Thu_tu { get; set; }
        public Nullable<bool> Ton_kho { get; set; }
        public Nullable<int> ID_DANH_MUC_GIAY { get; set; }
        public Nullable<bool> Khong_con { get; set; }
        public string ten_mo_rong { get; set; }
    
        public virtual DANH_MUC_GIAY DANH_MUC_GIAY { get; set; }
    }
}
