//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_OFFSET_GIA_CONG
    {
        public int ID { get; set; }
        public string ten_may_in { get; set; }
        public string ten_nha_cung_cap { get; set; }
        public string ten_kho_in { get; set; }
        public Nullable<int> kho_in_rong_max { get; set; }
        public Nullable<int> kho_in_dai_max { get; set; }
        public Nullable<int> kho_in_rong_min { get; set; }
        public Nullable<int> kho_in_dai_min { get; set; }
        public Nullable<bool> tu_tro_nhip { get; set; }
        public Nullable<int> gia_cong_in { get; set; }
        public Nullable<int> so_mat_in_co_ban { get; set; }
        public Nullable<int> gia_in_moi_mat_vuot { get; set; }
        public Nullable<int> so_to_chay_bu_hao_co_ban { get; set; }
        public string thong_tin_nguoi_dung_may { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<int> thu_tu { get; set; }
        public Nullable<bool> khong_dung { get; set; }
    }
}
