//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_SAN_PHAM
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<double> Chieu_cat_rong { get; set; }
        public Nullable<double> Chieu_cat_cao { get; set; }
        public Nullable<int> Thu_tu { get; set; }
        public string dien_giai { get; set; }
        public Nullable<double> tran_le_tren { get; set; }
        public Nullable<double> tran_le_duoi { get; set; }
        public Nullable<double> tran_le_trong { get; set; }
        public Nullable<double> tran_le_ngoai { get; set; }
    }
}
