//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_XO_DONG_CUON
    {
        public int ID { get; set; }
        public string ten_vong_xoan { get; set; }
        public string kich_co_buoc { get; set; }
        public string mau_sac { get; set; }
        public string cho_do_day { get; set; }
        public Nullable<int> gia_mua_theo_met { get; set; }
        public Nullable<int> thu_tu { get; set; }
    }
}
