//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_UP_LOI_NHUAN_GIAY
    {
        public int ID_HANG_KHACH_HANG { get; set; }
        public int ID_DANH_MUC_GIAY { get; set; }
        public Nullable<int> Ty_le_mark_up { get; set; }
    
        public virtual DANH_MUC_GIAY DANH_MUC_GIAY { get; set; }
        public virtual HANG_KHACH_HANG HANG_KHACH_HANG { get; set; }
    }
}
