//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAY_IN_DIGI
    {
        public MAY_IN_DIGI()
        {
            this.TO_IN_MAY_DIGI = new HashSet<TO_IN_MAY_DIGI>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Thong_tin_toc_do { get; set; }
        public Nullable<int> BHR { get; set; }
        public Nullable<int> Click4C20PCTA3 { get; set; }
        public Nullable<int> Click1C20PCTA3 { get; set; }
        public Nullable<int> Click6C20PCTA3 { get; set; }
        public Nullable<int> Phi_phe_pham_san_sang { get; set; }
        public Nullable<double> Thoi_gian_san_sang { get; set; }
        public Nullable<int> Thoi_gian_du_lieu_bien_doi { get; set; }
        public Nullable<int> Click_A4_4M { get; set; }
        public Nullable<int> Click_A4_1M { get; set; }
        public Nullable<int> Click_A4_6M { get; set; }
        public Nullable<int> toc_do_hieu_qua { get; set; }
        public Nullable<int> thu_tu { get; set; }
        public string kho_in_min { get; set; }
        public string kho_in_max { get; set; }
    
        public virtual ICollection<TO_IN_MAY_DIGI> TO_IN_MAY_DIGI { get; set; }
    }
}
