//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOI_DUNG
    {
        public int ID { get; set; }
        public string ten { get; set; }
        public string cho_hang_khach_hang { get; set; }
        public Nullable<bool> hieu_luc { get; set; }
        public string form_co_the_mo { get; set; }
    }
}
