//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_LOT_MO_PHANG
    {
        public int ID { get; set; }
        public string ten { get; set; }
        public string ma_nha_cung_cap { get; set; }
        public string ten_nha_cung_cap { get; set; }
        public string dien_giai { get; set; }
        public Nullable<int> gia_mua_to { get; set; }
        public Nullable<int> thu_tu { get; set; }
    }
}
