//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEU_CAU_TINH_GIA_IN
    {
        public int ID { get; set; }
        public Nullable<int> ID_NGUOI_DUNG { get; set; }
        public Nullable<System.DateTime> ngay_yeu_cau { get; set; }
        public string ho_ten { get; set; }
        public string cong_ty { get; set; }
        public string so_dien_thoai { get; set; }
        public string email { get; set; }
        public string tham_chieu_ticket { get; set; }
        public string noi_dung { get; set; }
        public string phan_cho_nhan_vien { get; set; }
        public Nullable<int> tinh_trang { get; set; }
    }
}
